import type { EnemyDef, Wave, ActorKind } from './types';

export const ENEMY_DEFS: Record<string, EnemyDef> = {
  plains_bandit: {
    kind: 'plains_bandit',
    name: 'Plains Bandit',
    color: '#6b4f2a',
    initial: 'B',
    hp: 160,
    armor: 5,
    magicResist: 0,
    moveSpeed: 100,
    damage: 8,
    attackRange: 50,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [5, 15],
    dropWeapon: null,
    dropWeaponChance: 0.1,
    width: 40,
    height: 60,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_archer: {
    kind: 'bandit_archer',
    name: 'Bandit Archer',
    color: '#8b6b3a',
    initial: 'A',
    hp: 120,
    armor: 0,
    magicResist: 0,
    moveSpeed: 90,
    damage: 12,
    attackRange: 50,
    attackCooldownMs: 2000,
    ai: 'archer',
    dropCopper: [5, 15],
    dropWeapon: 'rock',
    dropWeaponChance: 0.2,
    width: 40,
    height: 60,
    isRanged: true,
    projectileSpeed: 400,
    projectileRange: 300,
  },
  wolf: {
    kind: 'wolf',
    name: 'Wolf',
    color: '#6e6e6e',
    initial: 'W',
    hp: 120,
    armor: 0,
    magicResist: 0,
    moveSpeed: 160,
    damage: 10,
    attackRange: 50,
    attackCooldownMs: 1500,
    ai: 'packer',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 38,
    height: 50,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_brute: {
    kind: 'bandit_brute',
    name: 'Bandit Brute',
    color: '#3e2a14',
    initial: 'R',
    hp: 320,
    armor: 15,
    magicResist: 0,
    moveSpeed: 70,
    damage: 18,
    attackRange: 60,
    attackCooldownMs: 2500,
    ai: 'brute',
    dropCopper: [20, 40],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 50,
    height: 70,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_king: {
    kind: 'bandit_king',
    name: 'Bandit King',
    color: '#8a0f0f',
    initial: 'K',
    hp: 3200,
    armor: 20,
    magicResist: 10,
    moveSpeed: 90,
    damage: 35,
    attackRange: 80,
    attackCooldownMs: 1000,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 80,
    height: 120,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  wolf_pet: {
    kind: 'wolf_pet',
    name: 'Wolf Pet',
    color: '#a3a3a3',
    initial: 'P',
    hp: 200,
    armor: 0,
    magicResist: 0,
    moveSpeed: 160,
    damage: 15,
    attackRange: 45,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 35,
    height: 45,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  drowned_spawn: {
    kind: 'drowned_spawn',
    name: 'Drowned Spawn',
    color: '#134e4a',
    initial: 'S',
    hp: 600,
    armor: 0,
    magicResist: 0,
    moveSpeed: 110,
    damage: 20,
    attackRange: 50,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 40,
    height: 60,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  rotting_husk: {
    kind: 'rotting_husk',
    name: 'Rotting Husk',
    color: '#4d7c0f',
    initial: 'H',
    hp: 200,
    armor: 0,
    magicResist: 0,
    moveSpeed: 80,
    damage: 10,
    attackRange: 50,
    attackCooldownMs: 1500,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 38,
    height: 55,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
};

export const STAGE_WAVES: Wave[] = [
  {
    triggerX: 400,
    enemies: [
      { kind: 'plains_bandit' as ActorKind, count: 2 },
    ],
    triggered: false,
    cleared: false,
  },
  {
    triggerX: 900,
    enemies: [
      { kind: 'plains_bandit' as ActorKind, count: 3 },
      { kind: 'bandit_archer' as ActorKind, count: 1 },
    ],
    triggered: false,
    cleared: false,
  },
  {
    triggerX: 1600,
    enemies: [
      { kind: 'wolf' as ActorKind, count: 2 },
    ],
    triggered: false,
    cleared: false,
  },
  {
    triggerX: 2400,
    enemies: [
      { kind: 'plains_bandit' as ActorKind, count: 2 },
      { kind: 'bandit_archer' as ActorKind, count: 2 },
    ],
    triggered: false,
    cleared: false,
  },
  {
    triggerX: 3200,
    enemies: [
      { kind: 'bandit_brute' as ActorKind, count: 1 },
      { kind: 'wolf' as ActorKind, count: 2 },
    ],
    triggered: false,
    cleared: false,
  },
  {
    triggerX: 3800,
    enemies: [
      { kind: 'bandit_king' as ActorKind, count: 1 },
    ],
    triggered: false,
    cleared: false,
  },
];
