import type { EnemyDef, Wave, WaveEnemy, ActorKind, GuildId, StageId } from './types';

export const ENEMY_DEFS: Record<string, EnemyDef> = {
  plains_bandit: {
    kind: 'plains_bandit',
    name: 'Plains Bandit',
    color: '#6b4f2a',
    initial: 'B',
    hp: 128,
    armor: 5,
    magicResist: 0,
    moveSpeed: 100,
    damage: 9,
    attackRange: 50,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [5, 15],
    dropWeapon: null,
    dropWeaponChance: 0.1,
    width: 40,
    height: 60,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_archer: {
    kind: 'bandit_archer',
    name: 'Bandit Archer',
    color: '#8b6b3a',
    initial: 'A',
    hp: 96,
    armor: 0,
    magicResist: 0,
    moveSpeed: 90,
    damage: 14,
    attackRange: 50,
    attackCooldownMs: 2000,
    ai: 'archer',
    dropCopper: [5, 15],
    dropWeapon: 'rock',
    dropWeaponChance: 0.2,
    width: 40,
    height: 60,
    isRanged: true,
    projectileSpeed: 400,
    projectileRange: 300,
  },
  wolf: {
    kind: 'wolf',
    name: 'Wolf',
    color: '#6e6e6e',
    initial: 'W',
    hp: 96,
    armor: 0,
    magicResist: 0,
    moveSpeed: 160,
    damage: 12,
    attackRange: 50,
    attackCooldownMs: 1500,
    ai: 'packer',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 38,
    height: 50,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_brute: {
    kind: 'bandit_brute',
    name: 'Bandit Brute',
    color: '#3e2a14',
    initial: 'R',
    hp: 256,
    armor: 15,
    magicResist: 0,
    moveSpeed: 70,
    damage: 21,
    attackRange: 60,
    attackCooldownMs: 2500,
    ai: 'brute',
    dropCopper: [20, 40],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 50,
    height: 70,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  bandit_king: {
    kind: 'bandit_king',
    name: 'Bandit King',
    color: '#8a0f0f',
    initial: 'K',
    hp: 2240,
    armor: 20,
    magicResist: 10,
    moveSpeed: 90,
    damage: 35,
    attackRange: 80,
    attackCooldownMs: 1000,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 80,
    height: 120,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  wolf_pet: {
    kind: 'wolf_pet',
    name: 'Wolf Pet',
    color: '#a3a3a3',
    initial: 'P',
    hp: 200,
    armor: 0,
    magicResist: 0,
    moveSpeed: 160,
    damage: 15,
    attackRange: 45,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 35,
    height: 45,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  drowned_spawn: {
    kind: 'drowned_spawn',
    name: 'Drowned Spawn',
    color: '#134e4a',
    initial: 'S',
    hp: 480,
    armor: 0,
    magicResist: 0,
    moveSpeed: 110,
    damage: 23,
    attackRange: 50,
    attackCooldownMs: 1200,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 40,
    height: 60,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  rotting_husk: {
    kind: 'rotting_husk',
    name: 'Rotting Husk',
    color: '#4d7c0f',
    initial: 'H',
    hp: 160,
    armor: 0,
    magicResist: 0,
    moveSpeed: 80,
    damage: 12,
    attackRange: 50,
    attackCooldownMs: 1500,
    ai: 'chaser',
    dropCopper: [0, 0],
    dropWeapon: null,
    dropWeaponChance: 0,
    width: 38,
    height: 55,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
  },
  giant_blue_wolf: {
    kind: 'giant_blue_wolf',
    name: 'Giant Blue Wolf',
    color: '#3b82f6',
    initial: 'W',
    hp: 1400,
    armor: 8,
    magicResist: 5,
    moveSpeed: 180,
    damage: 28,
    attackRange: 70,
    attackCooldownMs: 1200,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'rock',
    dropWeaponChance: 1.0,
    width: 90,
    height: 100,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.5, attackSpeedMult: 1.3, damageMult: 1.1,
        summons: [{ kind: 'wolf', count: 4 }], abilities: [] },
    ],
  },
  vampire_lord: {
    kind: 'vampire_lord',
    name: 'Vampire Lord',
    color: '#7c3aed',
    initial: 'V',
    hp: 1800,
    armor: 10,
    magicResist: 15,
    moveSpeed: 130,
    damage: 30,
    attackRange: 65,
    attackCooldownMs: 1000,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 50,
    height: 80,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.6, attackSpeedMult: 1.1, damageMult: 1.1,
        summons: [{ kind: 'vampire_lord', count: 0 }], abilities: [] },
      { hpThreshold: 0.3, attackSpeedMult: 1.3, damageMult: 1.5,
        summons: [], abilities: [] },
    ],
  },
  cult_high_priest: {
    kind: 'cult_high_priest',
    name: 'Cult High Priest',
    color: '#065f46',
    initial: 'P',
    hp: 1600,
    armor: 5,
    magicResist: 20,
    moveSpeed: 85,
    damage: 26,
    attackRange: 60,
    attackCooldownMs: 1400,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'rock',
    dropWeaponChance: 1.0,
    width: 50,
    height: 80,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.5, attackSpeedMult: 1.1, damageMult: 1.1,
        summons: [{ kind: 'drowned_spawn', count: 6 }], abilities: [] },
      { hpThreshold: 0.25, attackSpeedMult: 1.2, damageMult: 1.5,
        summons: [], abilities: [] },
    ],
  },
  elder_druid: {
    kind: 'elder_druid',
    name: 'Elder Druid',
    color: '#166534',
    initial: 'D',
    hp: 1500,
    armor: 8,
    magicResist: 12,
    moveSpeed: 95,
    damage: 24,
    attackRange: 60,
    attackCooldownMs: 1300,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 55,
    height: 80,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.4, attackSpeedMult: 1.4, damageMult: 1.4,
        summons: [{ kind: 'wolf', count: 4 }], abilities: [] },
    ],
  },
  plague_darkmage: {
    kind: 'plague_darkmage',
    name: 'Plague Darkmage',
    color: '#4c1d95',
    initial: 'M',
    hp: 2000,
    armor: 5,
    magicResist: 25,
    moveSpeed: 80,
    damage: 32,
    attackRange: 55,
    attackCooldownMs: 1100,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'rock',
    dropWeaponChance: 1.0,
    width: 50,
    height: 75,
    isRanged: true,
    projectileSpeed: 350,
    projectileRange: 280,
    phases: [
      { hpThreshold: 0.6, attackSpeedMult: 1.1, damageMult: 1.2,
        summons: [{ kind: 'rotting_husk', count: 4 }], abilities: [] },
      { hpThreshold: 0.3, attackSpeedMult: 1.4, damageMult: 1.3,
        summons: [], abilities: [] },
    ],
  },
  warlord: {
    kind: 'warlord',
    name: 'Warlord',
    color: '#b45309',
    initial: 'W',
    hp: 2500,
    armor: 25,
    magicResist: 10,
    moveSpeed: 110,
    damage: 40,
    attackRange: 75,
    attackCooldownMs: 900,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 60,
    height: 90,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.7, attackSpeedMult: 1.2, damageMult: 1.0,
        summons: [], abilities: [] },
      { hpThreshold: 0.4, attackSpeedMult: 1.3, damageMult: 1.3,
        summons: [{ kind: 'bandit_brute', count: 2 }], abilities: [] },
      { hpThreshold: 0.15, attackSpeedMult: 1.4, damageMult: 1.4,
        summons: [], abilities: [] },
    ],
  },
  shadow_master: {
    kind: 'shadow_master',
    name: 'Shadow Master',
    color: '#1e1b4b',
    initial: 'S',
    hp: 2200,
    armor: 12,
    magicResist: 18,
    moveSpeed: 150,
    damage: 36,
    attackRange: 65,
    attackCooldownMs: 800,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 45,
    height: 75,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.5, attackSpeedMult: 1.2, damageMult: 1.2,
        summons: [{ kind: 'plains_bandit', count: 3 }], abilities: [] },
      { hpThreshold: 0.25, attackSpeedMult: 2.0, damageMult: 1.4,
        summons: [], abilities: [] },
    ],
  },
  bandit_king_ii: {
    kind: 'bandit_king_ii',
    name: 'Bandit King II',
    color: '#991b1b',
    initial: 'K',
    hp: 3200,
    armor: 25,
    magicResist: 15,
    moveSpeed: 100,
    damage: 45,
    attackRange: 85,
    attackCooldownMs: 900,
    ai: 'boss',
    dropCopper: [0, 0],
    dropWeapon: 'club',
    dropWeaponChance: 1.0,
    width: 90,
    height: 130,
    isRanged: false,
    projectileSpeed: 0,
    projectileRange: 0,
    phases: [
      { hpThreshold: 0.66, attackSpeedMult: 1.2, damageMult: 1.1,
        summons: [{ kind: 'bandit_brute', count: 3 }], abilities: [] },
      { hpThreshold: 0.33, attackSpeedMult: 1.3, damageMult: 1.3,
        summons: [{ kind: 'bandit_king', count: 1 }], abilities: [] },
      { hpThreshold: 0.15, attackSpeedMult: 1.5, damageMult: 1.5,
        summons: [], abilities: [] },
    ],
  },
};

const LEVEL_STAT_MULT = (level: number) => ({
  hpMult: 1 + (level - 1) * 0.15,
  dmgMult: 1 + (level - 1) * 0.12,
});
export { LEVEL_STAT_MULT };

function w(triggerX: number, enemies: Wave['enemies']): Wave {
  return { triggerX, enemies, triggered: false, cleared: false };
}

function e(kind: ActorKind, count: number): WaveEnemy {
  return { kind, count };
}

function g(guild: GuildId, count: number, difficulty: number): WaveEnemy {
  return { guild, count, difficulty };
}

export const STAGE_WAVES: Record<StageId, Wave[]> = {
  assembly: [
    w(400,  [e('plains_bandit', 2)]),
    w(900,  [e('plains_bandit', 3), e('bandit_archer', 1)]),
    w(1400, [e('plains_bandit', 2), e('bandit_archer', 2)]),
    w(2000, [e('plains_bandit', 4), e('bandit_archer', 1)]),
    w(2600, [e('plains_bandit', 3), e('bandit_archer', 2)]),
    w(3800, [e('bandit_king', 1)]),
  ],
  market: [
    w(400,  [e('wolf', 3)]),
    w(900,  [e('wolf', 4), e('bandit_archer', 2)]),
    w(1400, [e('wolf', 5), e('bandit_archer', 2)]),
    w(2000, [e('wolf', 6), e('bandit_archer', 3)]),
    w(2600, [e('wolf', 4), e('bandit_archer', 4)]),
    w(3800, [e('giant_blue_wolf', 1)]),
  ],
  kitchen: [
    w(400,  [e('bandit_brute', 2)]),
    w(900,  [e('bandit_brute', 2), g('vampire', 2, 2)]),
    w(1400, [e('bandit_brute', 3), g('vampire', 2, 3)]),
    w(2000, [e('bandit_brute', 2), g('vampire', 4, 3)]),
    w(2600, [g('vampire', 4, 4)]),
    w(3800, [e('vampire_lord', 1)]),
  ],
  tower: [
    w(400,  [g('cultist', 3, 2)]),
    w(900,  [g('cultist', 2, 2), e('drowned_spawn', 3)]),
    w(1400, [g('cultist', 3, 3), e('drowned_spawn', 4)]),
    w(2000, [g('cultist', 4, 3), e('drowned_spawn', 2)]),
    w(2600, [g('cultist', 5, 4)]),
    w(3800, [e('cult_high_priest', 1)]),
  ],
  grove: [
    w(400,  [g('druid', 2, 2)]),
    w(900,  [g('druid', 2, 2), g('hunter', 2, 2)]),
    w(1400, [e('wolf', 2), g('hunter', 2, 3), g('druid', 1, 3)]),
    w(2000, [g('hunter', 4, 3), e('wolf', 2)]),
    w(2600, [g('druid', 3, 4), g('hunter', 2, 4)]),
    w(3800, [e('elder_druid', 1)]),
  ],
  catacombs: [
    w(400,  [g('leper', 3, 3)]),
    w(900,  [g('leper', 2, 3), e('rotting_husk', 3)]),
    w(1400, [g('darkmage', 2, 3), e('rotting_husk', 3)]),
    w(2000, [g('leper', 2, 4), g('darkmage', 2, 4)]),
    w(2600, [g('darkmage', 4, 4), e('rotting_husk', 2)]),
    w(3800, [e('plague_darkmage', 1)]),
  ],
  throne: [
    w(400,  [g('viking', 3, 4)]),
    w(900,  [g('knight', 2, 4), g('viking', 2, 4)]),
    w(1400, [g('knight', 3, 4), g('champion', 2, 4)]),
    w(2000, [g('viking', 2, 5), g('champion', 3, 5)]),
    w(2600, [g('knight', 2, 5), g('champion', 2, 5), g('viking', 1, 5)]),
    w(3800, [e('warlord', 1)]),
  ],
  docks: [
    w(400,  [e('bandit_brute', 2)]),
    w(900,  [g('adventurer', 3, 4), e('bandit_brute', 2)]),
    w(1400, [g('mage', 3, 4), g('monk', 3, 4)]),
    w(2000, [g('prophet', 3, 5), g('viking', 3, 5)]),
    w(2600, [g('master', 2, 5), g('champion', 2, 5)]),
    w(3800, [e('shadow_master', 1)]),
  ],
  rooftops: [
    w(400,  [e('plains_bandit', 3), e('wolf', 3)]),
    w(900,  [g('vampire', 3, 5), e('bandit_brute', 2)]),
    w(1400, [g('darkmage', 3, 5), e('rotting_husk', 3)]),
    w(2000, [g('knight', 2, 5), g('viking', 2, 5), g('champion', 2, 5)]),
    w(2600, [g('cultist', 4, 5), e('drowned_spawn', 4)]),
    w(3800, [e('bandit_king_ii', 1)]),
  ],
};
