import type { GuildDef, AbilityDef, ResourceDef } from './types';

function makeAbility(overrides: Partial<AbilityDef> & { id: string; name: string; combo: string }): AbilityDef {
  return {
    baseDamage: 0,
    scaleStat: null,
    scaleAmount: 0,
    cooldownMs: 3000,
    cost: 0,
    castTimeMs: 0,
    range: 60,
    aoeRadius: 0,
    damageType: 'physical',
    knockdown: false,
    knockbackForce: 0,
    effects: {},
    isHeal: false,
    isProjectile: false,
    projectileSpeed: 400,
    isTeleport: false,
    teleportDist: 0,
    isSummon: false,
    isChannel: false,
    channelDurationMs: 0,
    isGroundTarget: false,
    piercing: false,
    description: '',
    vfxColor: '#ffffff',
    ...overrides,
  };
}

const staminaResource: ResourceDef = {
  name: 'Stamina',
  max: 100,
  startValue: 100,
  regenIdle: 5,
  regenCombat: 2,
  decayRate: 0,
  color: '#f59e0b',
};

export const GUILDS: GuildDef[] = [
  {
    id: 'adventurer',
    name: 'Adventurer',
    color: '#c9a961',
    initial: 'A',
    stats: { STR: 14, DEX: 12, CON: 14, INT: 8, WIS: 10, CHA: 10 },
    hpMax: 120,
    armor: 10,
    magicResist: 5,
    moveSpeed: 140,
    jumpPower: 600,
    damageType: 'physical',
    description: 'Generalist bruiser with balanced stats and utility',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.65,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.35,
      abilities: {
        1: { priority: 5, useAtCloseRange: true },
        2: { priority: 7, useAtCloseRange: true },
        3: { priority: 9, maxHpPct: 0.6, retreatToUse: true },
        4: { priority: 4, useAtLongRange: true },
        5: { priority: 8, minHpPct: 0.3 },
        rmb: { priority: 6, maxHpPct: 0.7 },
      },
    },
    resource: staminaResource,
    abilities: [
      makeAbility({ id: 'rallying_cry', name: 'Rallying Cry', combo: 'down,down,attack', cooldownMs: 15000, cost: 30, aoeRadius: 100, effects: { speed_boost: { magnitude: 0.15, durationMs: 4000 }, damage_boost: { magnitude: 0.1, durationMs: 4000 } }, vfxColor: '#f59e0b', description: '+15% speed/dmg to self and allies 4s' }),
      makeAbility({ id: 'slash', name: 'Slash', combo: 'right,right,attack', baseDamage: 30, scaleStat: 'STR', scaleAmount: 0.7, cooldownMs: 2000, cost: 10, range: 80, aoeRadius: 60, damageType: 'physical', knockbackForce: 80, vfxColor: '#c9a961', description: 'Short-range cone melee, 80u' }),
      makeAbility({ id: 'bandage', name: 'Bandage', combo: 'down,up,attack', baseDamage: 50, scaleStat: 'CON', scaleAmount: 0.5, cooldownMs: 20000, cost: 25, isHeal: true, isChannel: true, channelDurationMs: 1500, vfxColor: '#22c55e', description: 'Self-heal channel 1.5s' }),
      makeAbility({ id: 'quickshot', name: 'Quickshot', combo: 'left,right,attack', baseDamage: 35, scaleStat: 'DEX', scaleAmount: 0.6, cooldownMs: 4000, cost: 15, isProjectile: true, projectileSpeed: 500, range: 350, vfxColor: '#c9a961', description: 'Ranged projectile 350u' }),
      makeAbility({ id: 'adrenaline_rush', name: 'Adrenaline Rush', combo: 'down,up,down,up,attack', cooldownMs: 75000, cost: 40, aoeRadius: 0, effects: { attack_speed_boost: { magnitude: 0.4, durationMs: 6000 }, damage_boost: { magnitude: 0.25, durationMs: 6000 } }, vfxColor: '#f97316', description: '6s: +40% AS, +25% dmg, slow/root immune' }),
    ],
    rmb: makeAbility({ id: 'second_wind', name: 'Second Wind', combo: 'block+attack', cooldownMs: 20000, cost: 0, vfxColor: '#f59e0b', description: 'Restore 30% stamina' }),
  },
  {
    id: 'knight',
    name: 'Knight',
    color: '#a8dadc',
    initial: 'K',
    stats: { STR: 14, DEX: 8, CON: 18, INT: 8, WIS: 12, CHA: 10 },
    hpMax: 180,
    armor: 25,
    magicResist: 10,
    moveSpeed: 120,
    jumpPower: 500,
    damageType: 'physical',
    description: 'Heavy tank with taunts and crowd control',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.6,
      blockOnReaction: true,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.15,
      abilities: {
        1: { priority: 8, minResourcePct: 0.35, useAtCloseRange: true },
        2: { priority: 7, useAtCloseRange: true },
        3: { priority: 5, useAtCloseRange: true },
        4: { priority: 6, maxHpPct: 0.7 },
        5: { priority: 9, maxHpPct: 0.4 },
        rmb: { priority: 8, maxHpPct: 0.5 },
      },
    },
    resource: {
      name: 'Resolve',
      max: 100,
      startValue: 0,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: 1,
      color: '#60a5fa',
    },
    abilities: [
      makeAbility({ id: 'holy_rebuke', name: 'Holy Rebuke', combo: 'down,down,attack', baseDamage: 60, scaleStat: 'STR', scaleAmount: 1.0, cooldownMs: 14000, cost: 35, aoeRadius: 120, effects: { stun: { magnitude: 1, durationMs: 1000 } }, damageType: 'holy', vfxColor: '#fde68a', description: 'PB AoE 120u, stun 1s' }),
      makeAbility({ id: 'valorous_strike', name: 'Valorous Strike', combo: 'right,right,attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 0.8, cooldownMs: 3000, cost: 15, range: 60, damageType: 'physical', vfxColor: '#a8dadc', description: 'Melee, +10 resolve on hit' }),
      makeAbility({ id: 'taunt', name: 'Taunt', combo: 'down,up,attack', cooldownMs: 8000, cost: 20, aoeRadius: 120, effects: { taunt: { magnitude: 1, durationMs: 3000 } }, vfxColor: '#fbbf24', description: '120u cone, force enemies to attack knight 3s' }),
      makeAbility({ id: 'shield_wall', name: 'Shield Wall', combo: 'left,right,attack', cooldownMs: 20000, cost: 30, aoeRadius: 100, effects: { damage_reduction: { magnitude: 0.3, durationMs: 3000 } }, vfxColor: '#93c5fd', description: '100u radius, 30% dmg reduction to allies 3s' }),
      makeAbility({ id: 'last_stand', name: 'Last Stand', combo: 'down,up,down,up,attack', cooldownMs: 90000, cost: 50, effects: { shield: { magnitude: 999, durationMs: 8000 }, damage_boost: { magnitude: 0.5, durationMs: 8000 } }, vfxColor: '#fbbf24', description: '8s: cannot drop below 1HP; +50% dmg; ends with 25% self-heal' }),
    ],
    rmb: makeAbility({ id: 'shield_block', name: 'Shield Block', combo: 'block+attack', cooldownMs: 15000, cost: 0, effects: { damage_reduction: { magnitude: 0.5, durationMs: 2000 } }, vfxColor: '#a8dadc', description: '50% dmg reduction 2s' }),
  },
  {
    id: 'mage',
    name: 'Mage',
    color: '#8e6dc8',
    initial: 'M',
    stats: { STR: 6, DEX: 10, CON: 8, INT: 20, WIS: 14, CHA: 10 },
    hpMax: 80,
    armor: 3,
    magicResist: 15,
    moveSpeed: 130,
    jumpPower: 550,
    damageType: 'magical',
    description: 'Ranged burst caster with frost and teleport',
    strategy: {
      preferRange: 'long',
      aggressionPct: 0.35,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.4,
      abilities: {
        1: { priority: 8, useAtCloseRange: true },
        2: { priority: 6, useAtLongRange: true },
        3: { priority: 9, maxHpPct: 0.5, retreatToUse: true },
        4: { priority: 7, useAtLongRange: true },
        5: { priority: 8, minResourcePct: 0.5 },
        rmb: { priority: 9, maxHpPct: 0.6, retreatToUse: true },
      },
    },
    resource: {
      name: 'Mana',
      max: 200,
      startValue: 200,
      regenIdle: 5,
      regenCombat: 2,
      decayRate: 0,
      color: '#818cf8',
    },
    abilities: [
      makeAbility({ id: 'ice_nova', name: 'Ice Nova', combo: 'down,down,attack', baseDamage: 80, scaleStat: 'INT', scaleAmount: 1.5, cooldownMs: 14000, cost: 50, aoeRadius: 120, effects: { root: { magnitude: 1, durationMs: 1500 } }, damageType: 'magical', vfxColor: '#93c5fd', description: 'PB AoE 120u, root 1.5s' }),
      makeAbility({ id: 'frostbolt', name: 'Frostbolt', combo: 'right,right,attack', baseDamage: 40, scaleStat: 'INT', scaleAmount: 0.8, cooldownMs: 3000, cost: 20, isProjectile: true, projectileSpeed: 450, range: 400, effects: { slow: { magnitude: 0.3, durationMs: 2000 } }, damageType: 'magical', vfxColor: '#93c5fd', description: 'Projectile 400u, 30% slow 2s' }),
      makeAbility({ id: 'blink', name: 'Blink', combo: 'down,up,attack', cooldownMs: 10000, cost: 40, isTeleport: true, teleportDist: 240, vfxColor: '#818cf8', description: 'Teleport 240u, breaks roots/slows' }),
      makeAbility({ id: 'arcane_shard', name: 'Arcane Shard', combo: 'left,right,attack', baseDamage: 60, scaleStat: 'INT', scaleAmount: 1.2, cooldownMs: 5000, cost: 30, isProjectile: true, projectileSpeed: 500, range: 500, piercing: true, damageType: 'magical', vfxColor: '#c084fc', description: 'Piercing projectile 500u' }),
      makeAbility({ id: 'meteor', name: 'Meteor', combo: 'down,up,down,up,attack', baseDamage: 200, scaleStat: 'INT', scaleAmount: 3.0, cooldownMs: 90000, cost: 100, isGroundTarget: true, castTimeMs: 1200, aoeRadius: 160, damageType: 'magical', knockdown: true, knockbackForce: 200, vfxColor: '#ef4444', description: 'Ground-target, 1.2s delay, 160u AoE' }),
    ],
    rmb: makeAbility({ id: 'short_teleport', name: 'Short Teleport', combo: 'block+attack', cooldownMs: 8000, cost: 20, isTeleport: true, teleportDist: 120, vfxColor: '#818cf8', description: '120u step toward cursor' }),
  },
  {
    id: 'druid',
    name: 'Druid',
    color: '#4caf50',
    initial: 'D',
    stats: { STR: 8, DEX: 10, CON: 14, INT: 14, WIS: 18, CHA: 12 },
    hpMax: 110,
    armor: 8,
    magicResist: 12,
    moveSpeed: 130,
    jumpPower: 550,
    damageType: 'nature',
    description: 'Healer-shifter with bear/wolf forms',
    strategy: {
      preferRange: 'mid',
      aggressionPct: 0.4,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.5,
      abilities: {
        1: { priority: 9, maxHpPct: 0.6, retreatToUse: true },
        2: { priority: 6, useAtLongRange: true },
        3: { priority: 9, maxHpPct: 0.7, retreatToUse: true },
        4: { priority: 7, maxHpPct: 0.6 },
        5: { priority: 8, maxHpPct: 0.4, retreatToUse: true },
        rmb: { priority: 4 },
      },
    },
    resource: {
      name: 'Essence',
      max: 100,
      startValue: 100,
      regenIdle: 4,
      regenCombat: 2,
      decayRate: 0,
      color: '#4caf50',
    },
    abilities: [
      makeAbility({ id: 'wild_growth', name: 'Wild Growth', combo: 'down,down,attack', baseDamage: 15, scaleStat: 'WIS', scaleAmount: 0.4, cooldownMs: 12000, cost: 35, aoeRadius: 100, isHeal: true, effects: { hot: { magnitude: 15, durationMs: 5000 } }, vfxColor: '#4caf50', description: 'PB 100u heal circle 5s' }),
      makeAbility({ id: 'entangle', name: 'Entangle', combo: 'right,right,attack', baseDamage: 20, scaleStat: 'INT', scaleAmount: 0.5, cooldownMs: 10000, cost: 25, isProjectile: true, projectileSpeed: 350, range: 350, effects: { root: { magnitude: 1, durationMs: 2000 } }, damageType: 'nature', vfxColor: '#65a30d', description: 'Projectile, root 2s' }),
      makeAbility({ id: 'rejuvenate', name: 'Rejuvenate', combo: 'down,up,attack', baseDamage: 30, scaleStat: 'WIS', scaleAmount: 0.8, cooldownMs: 4000, cost: 20, isHeal: true, effects: { hot: { magnitude: 40, durationMs: 6000 } }, range: 150, vfxColor: '#86efac', description: 'Heal + HoT on nearest ally' }),
      makeAbility({ id: 'cleanse', name: 'Cleanse', combo: 'left,right,attack', baseDamage: 40, scaleStat: 'WIS', scaleAmount: 0.6, cooldownMs: 8000, cost: 20, isHeal: true, range: 150, vfxColor: '#bbf7d0', description: 'Heal + remove 2 debuffs from ally' }),
      makeAbility({ id: 'tranquility', name: 'Tranquility', combo: 'down,up,down,up,attack', baseDamage: 50, scaleStat: 'WIS', scaleAmount: 0.8, cooldownMs: 120000, cost: 80, isHeal: true, isChannel: true, channelDurationMs: 4000, aoeRadius: 200, vfxColor: '#86efac', description: 'Channel 4s, 200u heal all allies' }),
    ],
    rmb: makeAbility({ id: 'shapeshift', name: 'Shapeshift', combo: 'block+attack', cooldownMs: 5000, cost: 20, vfxColor: '#4caf50', description: 'Toggle bear/wolf form' }),
  },
  {
    id: 'hunter',
    name: 'Hunter',
    color: '#8d6e63',
    initial: 'H',
    stats: { STR: 10, DEX: 18, CON: 12, INT: 8, WIS: 10, CHA: 10 },
    hpMax: 100,
    armor: 6,
    magicResist: 5,
    moveSpeed: 140,
    jumpPower: 580,
    damageType: 'physical',
    description: 'Marksman with wolf pet',
    strategy: {
      preferRange: 'long',
      aggressionPct: 0.4,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.35,
      abilities: {
        1: { priority: 9, maxHpPct: 0.5, retreatToUse: true },
        2: { priority: 6, useAtLongRange: true },
        3: { priority: 8, useAtLongRange: true },
        4: { priority: 5, useAtLongRange: true },
        5: { priority: 7, minResourcePct: 0.5 },
        rmb: { priority: 3 },
      },
    },
    resource: {
      name: 'Focus',
      max: 100,
      startValue: 100,
      regenIdle: 3,
      regenCombat: 3,
      decayRate: 0,
      color: '#a3e635',
    },
    abilities: [
      makeAbility({ id: 'disengage', name: 'Disengage', combo: 'down,down,attack', cooldownMs: 10000, cost: 20, effects: { blind: { magnitude: 1, durationMs: 1000 } }, aoeRadius: 60, vfxColor: '#a3e635', description: 'Leap back 150u, blind 1s smoke' }),
      makeAbility({ id: 'piercing_volley', name: 'Piercing Volley', combo: 'right,right,attack', baseDamage: 25, scaleStat: 'DEX', scaleAmount: 0.4, cooldownMs: 6000, cost: 25, isProjectile: true, projectileSpeed: 600, range: 450, piercing: true, damageType: 'physical', vfxColor: '#a3e635', description: '3-arrow line, 450u' }),
      makeAbility({ id: 'aimed_shot', name: 'Aimed Shot', combo: 'down,up,attack', baseDamage: 50, scaleStat: 'DEX', scaleAmount: 1.0, cooldownMs: 3000, cost: 15, isProjectile: true, projectileSpeed: 700, range: 500, castTimeMs: 500, damageType: 'physical', vfxColor: '#fbbf24', description: '0.5s draw, 500u range, +15% crit' }),
      makeAbility({ id: 'bear_trap', name: 'Bear Trap', combo: 'left,right,attack', baseDamage: 40, scaleStat: 'DEX', scaleAmount: 0.5, cooldownMs: 12000, cost: 20, isGroundTarget: true, effects: { root: { magnitude: 1, durationMs: 1500 } }, vfxColor: '#8d6e63', description: 'Ground trap, root 1.5s on trigger' }),
      makeAbility({ id: 'rain_of_arrows', name: 'Rain of Arrows', combo: 'down,up,down,up,attack', baseDamage: 20, scaleStat: 'DEX', scaleAmount: 0.3, cooldownMs: 80000, cost: 50, isChannel: true, channelDurationMs: 3000, aoeRadius: 150, effects: { slow: { magnitude: 0.3, durationMs: 500 } }, damageType: 'physical', vfxColor: '#a3e635', description: 'Channel 3s — rains arrows 200u in front, 6 pulses' }),
    ],
    rmb: makeAbility({ id: 'pet_command', name: 'Pet Command', combo: 'block+attack', cooldownMs: 0, cost: 0, vfxColor: '#a3e635', description: 'Move pet / cycle AI mode' }),
  },
  {
    id: 'monk',
    name: 'Monk',
    color: '#d9a441',
    initial: 'M',
    stats: { STR: 10, DEX: 18, CON: 12, INT: 8, WIS: 14, CHA: 10 },
    hpMax: 100,
    armor: 7,
    magicResist: 10,
    moveSpeed: 160,
    jumpPower: 620,
    damageType: 'physical',
    description: 'Chi-based melee assassin with fastest move speed',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.8,
      blockOnReaction: true,
      resourceStrategy: 'hoard',
      retreatBelowHpPct: 0.2,
      abilities: {
        1: { priority: 8, retreatToUse: true },
        2: { priority: 7, useAtCloseRange: true },
        3: { priority: 5, useAtCloseRange: true },
        4: { priority: 9, minResourcePct: 0.6, useAtCloseRange: true },
        5: { priority: 8, minResourcePct: 1.0 },
        rmb: { priority: 7 },
      },
    },
    resource: {
      name: 'Chi',
      max: 5,
      startValue: 0,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: 0,
      color: '#fcd34d',
    },
    abilities: [
      makeAbility({ id: 'serenity', name: 'Serenity', combo: 'down,down,attack', cooldownMs: 14000, cost: 2, effects: { untargetable: { magnitude: 1, durationMs: 1000 }, speed_boost: { magnitude: 0.3, durationMs: 3000 } }, vfxColor: '#fcd34d', description: 'Untargetable 1s, cleanse CC, +30% speed 3s' }),
      makeAbility({ id: 'flying_kick', name: 'Flying Kick', combo: 'right,right,attack', baseDamage: 40, scaleStat: 'DEX', scaleAmount: 0.8, cooldownMs: 5000, cost: 1, range: 150, knockdown: true, knockbackForce: 100, vfxColor: '#f59e0b', description: 'Dash 150u, knockup 0.5s' }),
      makeAbility({ id: 'jab', name: 'Jab', combo: 'down,up,attack', baseDamage: 25, scaleStat: 'DEX', scaleAmount: 0.6, cooldownMs: 1000, cost: 0, range: 50, damageType: 'physical', vfxColor: '#d9a441', description: 'Basic melee, generates 1 chi' }),
      makeAbility({ id: 'five_point_palm', name: 'Five-Point Palm', combo: 'left,right,attack', baseDamage: 80, scaleStat: 'DEX', scaleAmount: 1.2, cooldownMs: 8000, cost: 3, range: 60, damageType: 'physical', vfxColor: '#ef4444', description: 'Melee + delayed detonation 4s (+40 dmg)' }),
      makeAbility({ id: 'dragons_fury', name: "Dragon's Fury", combo: 'down,up,down,up,attack', baseDamage: 40, scaleStat: 'DEX', scaleAmount: 0.5, cooldownMs: 90000, cost: 5, isChannel: true, channelDurationMs: 2000, range: 60, effects: { stun: { magnitude: 1, durationMs: 1500 } }, vfxColor: '#f97316', description: '2s channel, 5 strikes, final stun 1.5s' }),
    ],
    rmb: makeAbility({ id: 'monk_parry', name: 'Parry', combo: 'block+attack', cooldownMs: 10000, cost: 0, vfxColor: '#fcd34d', description: '0.3s parry window, stun on success' }),
  },
  {
    id: 'viking',
    name: 'Viking',
    color: '#b74c2a',
    initial: 'V',
    stats: { STR: 18, DEX: 10, CON: 16, INT: 6, WIS: 8, CHA: 8 },
    hpMax: 160,
    armor: 15,
    magicResist: 5,
    moveSpeed: 125,
    jumpPower: 520,
    damageType: 'physical',
    description: 'Rage-fueled berserker with lifesteal',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.9,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      abilities: {
        1: { priority: 7, minResourcePct: 0.25, useAtCloseRange: true },
        2: { priority: 6 },
        3: { priority: 8, minResourcePct: 0.3 },
        4: { priority: 5, useAtCloseRange: true },
        5: { priority: 9, maxHpPct: 0.3, minResourcePct: 0.6 },
        rmb: { priority: 6, useAtCloseRange: true },
      },
    },
    resource: {
      name: 'Rage',
      max: 100,
      startValue: 0,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: 2,
      color: '#ef4444',
    },
    abilities: [
      makeAbility({ id: 'whirlwind', name: 'Whirlwind', combo: 'down,down,attack', baseDamage: 25, scaleStat: 'STR', scaleAmount: 0.5, cooldownMs: 10000, cost: 25, isChannel: true, channelDurationMs: 2000, aoeRadius: 100, effects: { lifesteal: { magnitude: 0.2, durationMs: 2000 } }, damageType: 'physical', vfxColor: '#b74c2a', description: 'PB channel 2s, 100u radius, 20% lifesteal' }),
      makeAbility({ id: 'harpoon', name: 'Harpoon', combo: 'right,right,attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 0.7, cooldownMs: 12000, cost: 20, isProjectile: true, projectileSpeed: 500, range: 400, knockbackForce: -120, vfxColor: '#dc2626', description: 'Projectile, pulls target 120u' }),
      makeAbility({ id: 'bloodlust', name: 'Bloodlust', combo: 'down,up,attack', cooldownMs: 20000, cost: 30, effects: { attack_speed_boost: { magnitude: 0.25, durationMs: 8000 }, lifesteal: { magnitude: 0.15, durationMs: 8000 } }, vfxColor: '#991b1b', description: '8s: +25% AS, 15% lifesteal' }),
      makeAbility({ id: 'axe_swing', name: 'Axe Swing', combo: 'left,right,attack', baseDamage: 35, scaleStat: 'STR', scaleAmount: 0.8, cooldownMs: 2000, cost: 0, range: 60, aoeRadius: 60, damageType: 'physical', vfxColor: '#b74c2a', description: 'Melee cone 60u, builds rage' }),
      makeAbility({ id: 'undying_rage', name: 'Undying Rage', combo: 'down,up,down,up,attack', cooldownMs: 120000, cost: 60, effects: { shield: { magnitude: 999, durationMs: 6000 } }, vfxColor: '#7f1d1d', description: '6s: cannot die; dmg taken → 30% heal on expiry' }),
    ],
    rmb: makeAbility({ id: 'shield_bash', name: 'Shield Bash', combo: 'block+attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 0.5, cooldownMs: 12000, cost: 0, range: 60, knockbackForce: 150, damageType: 'physical', vfxColor: '#b74c2a', description: 'Melee + knockback' }),
  },
  {
    id: 'prophet',
    name: 'Prophet',
    color: '#f7e8a4',
    initial: 'P',
    stats: { STR: 8, DEX: 10, CON: 12, INT: 12, WIS: 18, CHA: 16 },
    hpMax: 100,
    armor: 6,
    magicResist: 14,
    moveSpeed: 125,
    jumpPower: 530,
    damageType: 'holy',
    description: 'Holy cleric and buffer supporting allies',
    strategy: {
      preferRange: 'mid',
      aggressionPct: 0.35,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.5,
      abilities: {
        1: { priority: 8, maxHpPct: 0.7 },
        2: { priority: 5, useAtLongRange: true },
        3: { priority: 6 },
        4: { priority: 7, useAtLongRange: true },
        5: { priority: 9, maxHpPct: 0.3, retreatToUse: true },
        rmb: { priority: 3 },
      },
    },
    resource: {
      name: 'Faith',
      max: 100,
      startValue: 100,
      regenIdle: 3,
      regenCombat: 2,
      decayRate: 0,
      color: '#fde68a',
    },
    abilities: [
      makeAbility({ id: 'prophetic_shield', name: 'Prophetic Shield', combo: 'down,down,attack', baseDamage: 80, scaleStat: 'WIS', scaleAmount: 1.2, cooldownMs: 15000, cost: 40, effects: { shield: { magnitude: 80, durationMs: 10000 } }, isHeal: false, vfxColor: '#fde68a', description: 'Shield absorbs 80+1.2×WIS; on break heal 30+0.5×WIS' }),
      makeAbility({ id: 'smite', name: 'Smite', combo: 'right,right,attack', baseDamage: 40, scaleStat: 'WIS', scaleAmount: 0.9, cooldownMs: 3000, cost: 15, isProjectile: true, projectileSpeed: 500, range: 450, damageType: 'holy', effects: { revealed: { magnitude: 1, durationMs: 3000 } }, vfxColor: '#fbbf24', description: 'Holy projectile, reveals 3s' }),
      makeAbility({ id: 'bless', name: 'Bless', combo: 'down,up,attack', cooldownMs: 8000, cost: 25, range: 200, effects: { damage_boost: { magnitude: 0.15, durationMs: 8000 }, speed_boost: { magnitude: 0.1, durationMs: 8000 } }, vfxColor: '#fde68a', description: 'Target ally +15% dmg, +10% speed 8s' }),
      makeAbility({ id: 'curse', name: 'Curse', combo: 'left,right,attack', cooldownMs: 12000, cost: 30, range: 300, effects: { curse: { magnitude: 1, durationMs: 6000 } }, vfxColor: '#7c3aed', description: 'Target +20% dmg taken, -15% dmg dealt 6s' }),
      makeAbility({ id: 'divine_intervention', name: 'Divine Intervention', combo: 'down,up,down,up,attack', cooldownMs: 150000, cost: 80, range: 200, effects: { untargetable: { magnitude: 1, durationMs: 3000 } }, isHeal: true, vfxColor: '#ffffff', description: 'Target invulnerable 3s; on expiry heal to 100%' }),
    ],
    rmb: makeAbility({ id: 'divine_insight', name: 'Divine Insight', combo: 'block+attack', cooldownMs: 30000, cost: 0, aoeRadius: 360, effects: { revealed: { magnitude: 1, durationMs: 4000 } }, vfxColor: '#fde68a', description: 'Reveal all enemies 360u for 4s' }),
  },
  {
    id: 'vampire',
    name: 'Vampire',
    color: '#7a1935',
    initial: 'V',
    stats: { STR: 10, DEX: 16, CON: 12, INT: 10, WIS: 8, CHA: 14 },
    hpMax: 110,
    armor: 8,
    magicResist: 10,
    moveSpeed: 145,
    jumpPower: 600,
    damageType: 'shadow',
    description: 'Lifesteal stalker with stealth mechanics',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.75,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.3,
      abilities: {
        1: { priority: 6, useAtLongRange: true },
        2: { priority: 7, useAtLongRange: true },
        3: { priority: 9, maxHpPct: 0.5, retreatToUse: true },
        4: { priority: 6, useAtCloseRange: true },
        5: { priority: 8, minResourcePct: 0.6 },
        rmb: { priority: 7, retreatToUse: true },
      },
    },
    resource: {
      name: 'Bloodpool',
      max: 100,
      startValue: 50,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: 1,
      color: '#dc2626',
    },
    abilities: [
      makeAbility({ id: 'hemorrhage', name: 'Hemorrhage', combo: 'down,down,attack', baseDamage: 15, scaleStat: 'DEX', scaleAmount: 0.3, cooldownMs: 14000, cost: 30, range: 300, isProjectile: true, projectileSpeed: 400, effects: { dot: { magnitude: 15, durationMs: 5000 } }, damageType: 'shadow', vfxColor: '#dc2626', description: 'Target DoT 5s, heal vampire 10% overflow' }),
      makeAbility({ id: 'shadow_step', name: 'Shadow Step', combo: 'right,right,attack', cooldownMs: 12000, cost: 25, isTeleport: true, teleportDist: 240, effects: { stealth: { magnitude: 1, durationMs: 1000 } }, vfxColor: '#7a1935', description: 'Teleport behind nearest enemy, 1s stealth' }),
      makeAbility({ id: 'blood_drain', name: 'Blood Drain', combo: 'down,up,attack', baseDamage: 50, scaleStat: 'DEX', scaleAmount: 1.0, cooldownMs: 10000, cost: 20, isChannel: true, channelDurationMs: 2000, range: 180, isHeal: true, damageType: 'shadow', vfxColor: '#dc2626', description: 'Channel 2s, heals full damage' }),
      makeAbility({ id: 'fang_strike', name: 'Fang Strike', combo: 'left,right,attack', baseDamage: 30, scaleStat: 'DEX', scaleAmount: 0.7, cooldownMs: 2000, cost: 0, range: 60, effects: { lifesteal: { magnitude: 0.4, durationMs: 0 } }, damageType: 'shadow', vfxColor: '#7a1935', description: 'Melee + heal 40% of damage' }),
      makeAbility({ id: 'nocturne', name: 'Nocturne', combo: 'down,up,down,up,attack', cooldownMs: 100000, cost: 60, effects: { stealth: { magnitude: 1, durationMs: 6000 }, speed_boost: { magnitude: 0.5, durationMs: 6000 } }, vfxColor: '#1e1b4b', description: '6s: invisible, +50% speed; next ability from stealth +100% dmg + fear' }),
    ],
    rmb: makeAbility({ id: 'mist_step', name: 'Mist Step', combo: 'block+attack', cooldownMs: 12000, cost: 20, isTeleport: true, teleportDist: 180, effects: { stealth: { magnitude: 1, durationMs: 1000 } }, vfxColor: '#7a1935', description: '180u reposition + 1s stealth' }),
  },
  {
    id: 'cultist',
    name: 'Cultist',
    color: '#2e4c3a',
    initial: 'C',
    stats: { STR: 6, DEX: 10, CON: 10, INT: 18, WIS: 10, CHA: 14 },
    hpMax: 90,
    armor: 4,
    magicResist: 12,
    moveSpeed: 125,
    jumpPower: 540,
    damageType: 'psychic',
    description: 'Sanity-inverse DoT caster; dangerous but unstable',
    strategy: {
      preferRange: 'mid',
      aggressionPct: 0.55,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      abilities: {
        1: { priority: 6 },
        2: { priority: 5, useAtLongRange: true },
        3: { priority: 8, useAtCloseRange: true },
        4: { priority: 6, useAtLongRange: true },
        5: { priority: 9 },
        rmb: { priority: 7 },
      },
    },
    resource: {
      name: 'Sanity',
      max: 100,
      startValue: 0,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: -2,
      color: '#134e4a',
    },
    abilities: [
      makeAbility({ id: 'summon_spawn', name: 'Summon Spawn', combo: 'down,down,attack', cooldownMs: 20000, cost: -30, isSummon: true, vfxColor: '#134e4a', description: 'Summon deep-spawn 150 HP, 20s' }),
      makeAbility({ id: 'whispers', name: 'Whispers', combo: 'right,right,attack', baseDamage: 30, scaleStat: 'INT', scaleAmount: 0.8, cooldownMs: 2000, cost: -10, isProjectile: true, projectileSpeed: 450, range: 400, effects: { silence: { magnitude: 1, durationMs: 1000 } }, damageType: 'psychic', vfxColor: '#2e4c3a', description: 'Projectile psychic, silence 1s' }),
      makeAbility({ id: 'madness', name: 'Madness', combo: 'down,up,attack', baseDamage: 30, scaleStat: 'INT', scaleAmount: 0.6, cooldownMs: 14000, cost: -25, aoeRadius: 360, effects: { stun: { magnitude: 1, durationMs: 2000 }, dot: { magnitude: 30, durationMs: 2000 } }, damageType: 'psychic', vfxColor: '#065f46', description: 'Target 360u, 2s confusion + DoT' }),
      makeAbility({ id: 'tendril_grasp', name: 'Tendril Grasp', combo: 'left,right,attack', baseDamage: 20, scaleStat: 'INT', scaleAmount: 0.4, cooldownMs: 10000, cost: -20, isGroundTarget: true, aoeRadius: 100, effects: { root: { magnitude: 1, durationMs: 1000 }, dot: { magnitude: 20, durationMs: 4000 } }, damageType: 'necrotic', vfxColor: '#166534', description: 'Ground tendril, root + DoT 4s' }),
      makeAbility({ id: 'open_the_gate', name: 'Open the Gate', combo: 'down,up,down,up,attack', baseDamage: 150, scaleStat: 'INT', scaleAmount: 2.0, cooldownMs: 120000, cost: -50, isChannel: true, channelDurationMs: 3000, aoeRadius: 240, knockdown: true, knockbackForce: -300, damageType: 'psychic', vfxColor: '#000000', description: '3s channel, 240u AoE, pulls to center' }),
    ],
    rmb: makeAbility({ id: 'gaze_abyss', name: 'Gaze into Abyss', combo: 'block+attack', cooldownMs: 25000, cost: 0, vfxColor: '#2e4c3a', description: 'Next ability: 0 sanity cost + 30% dmg' }),
  },
  {
    id: 'champion',
    name: 'Champion',
    color: '#a71d2a',
    initial: 'C',
    stats: { STR: 18, DEX: 12, CON: 14, INT: 6, WIS: 6, CHA: 8 },
    hpMax: 150,
    armor: 12,
    magicResist: 5,
    moveSpeed: 135,
    jumpPower: 560,
    damageType: 'physical',
    description: 'Forward-only bruiser; bloodtally stacks power',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.9,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      abilities: {
        1: { priority: 7, minResourcePct: 0.3 },
        2: { priority: 8 },
        3: { priority: 9, useAtCloseRange: true },
        4: { priority: 6, useAtCloseRange: true },
        5: { priority: 8, useAtCloseRange: true },
        rmb: { priority: 7 },
      },
    },
    resource: {
      name: 'Bloodtally',
      max: 10,
      startValue: 0,
      regenIdle: 0,
      regenCombat: 0,
      decayRate: 0,
      color: '#dc2626',
    },
    abilities: [
      makeAbility({ id: 'tithe_of_blood', name: 'Tithe of Blood', combo: 'down,down,attack', baseDamage: 50, scaleStat: 'STR', scaleAmount: 0.6, cooldownMs: 15000, cost: 3, isHeal: true, effects: { attack_speed_boost: { magnitude: 0.3, durationMs: 5000 } }, vfxColor: '#a71d2a', description: 'Consume stacks: +30% AS 5s, self-heal' }),
      makeAbility({ id: 'berserker_charge', name: 'Berserker Charge', combo: 'right,right,attack', baseDamage: 35, scaleStat: 'STR', scaleAmount: 0.6, cooldownMs: 10000, cost: 0, range: 240, knockdown: true, knockbackForce: 80, damageType: 'physical', vfxColor: '#dc2626', description: 'Dash 240u, knockup 0.5s, +1 bloodtally' }),
      makeAbility({ id: 'execute', name: 'Execute', combo: 'down,up,attack', baseDamage: 60, scaleStat: 'STR', scaleAmount: 0.8, cooldownMs: 6000, cost: 0, range: 60, damageType: 'physical', vfxColor: '#7f1d1d', description: 'Melee; ×2 if target <30% HP' }),
      makeAbility({ id: 'cleaver', name: 'Cleaver', combo: 'left,right,attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 0.9, cooldownMs: 2000, cost: 0, range: 60, aoeRadius: 60, damageType: 'physical', vfxColor: '#a71d2a', description: 'Melee arc 60u' }),
      makeAbility({ id: 'skullsplitter', name: 'Skullsplitter', combo: 'down,up,down,up,attack', baseDamage: 120, scaleStat: 'STR', scaleAmount: 2.0, cooldownMs: 90000, cost: 0, range: 60, knockdown: true, knockbackForce: 250, damageType: 'physical', vfxColor: '#450a0a', description: 'Heavy melee; on kill halve CD +3 bloodtally' }),
    ],
    rmb: makeAbility({ id: 'challenge', name: 'Challenge', combo: 'block+attack', cooldownMs: 18000, cost: 0, range: 300, effects: { taunt: { magnitude: 1.2, durationMs: 5000 } }, vfxColor: '#a71d2a', description: 'Target takes +20% dmg from champion 5s' }),
  },
  {
    id: 'darkmage',
    name: 'Darkmage',
    color: '#4a1458',
    initial: 'D',
    stats: { STR: 6, DEX: 10, CON: 10, INT: 18, WIS: 14, CHA: 8 },
    hpMax: 90,
    armor: 4,
    magicResist: 14,
    moveSpeed: 125,
    jumpPower: 540,
    damageType: 'shadow',
    description: 'Shadow controller with vision manipulation',
    strategy: {
      preferRange: 'long',
      aggressionPct: 0.3,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.4,
      abilities: {
        1: { priority: 5, useAtLongRange: true },
        2: { priority: 7, useAtLongRange: true },
        3: { priority: 6, useAtCloseRange: true },
        4: { priority: 6, useAtLongRange: true },
        5: { priority: 8, minResourcePct: 0.45 },
        rmb: { priority: 9, maxHpPct: 0.5, retreatToUse: true },
      },
    },
    resource: {
      name: 'Mana',
      max: 200,
      startValue: 200,
      regenIdle: 4,
      regenCombat: 2,
      decayRate: 0,
      color: '#a855f7',
    },
    abilities: [
      makeAbility({ id: 'darkness', name: 'Darkness', combo: 'down,down,attack', cooldownMs: 12000, cost: 35, isGroundTarget: true, aoeRadius: 150, effects: { blind: { magnitude: 0.9, durationMs: 4000 } }, vfxColor: '#1e1b4b', description: 'Zone: reduces vision 90u inside 4s' }),
      makeAbility({ id: 'grasping_shadow', name: 'Grasping Shadow', combo: 'right,right,attack', baseDamage: 30, scaleStat: 'INT', scaleAmount: 0.6, cooldownMs: 10000, cost: 30, isProjectile: true, projectileSpeed: 400, range: 400, effects: { root: { magnitude: 1, durationMs: 1500 } }, damageType: 'shadow', vfxColor: '#4a1458', description: 'Projectile, root 1.5s on first hit' }),
      makeAbility({ id: 'soul_leech', name: 'Soul Leech', combo: 'down,up,attack', baseDamage: 60, scaleStat: 'INT', scaleAmount: 1.0, cooldownMs: 14000, cost: 40, range: 360, damageType: 'shadow', effects: { lifesteal: { magnitude: 0.5, durationMs: 0 } }, vfxColor: '#6d28d9', description: 'Target 360u, restore 50% dmg as mana' }),
      makeAbility({ id: 'shadow_bolt', name: 'Shadow Bolt', combo: 'left,right,attack', baseDamage: 45, scaleStat: 'INT', scaleAmount: 0.9, cooldownMs: 3000, cost: 20, isProjectile: true, projectileSpeed: 480, range: 400, effects: { chilled: { magnitude: 5, durationMs: 3000 } }, damageType: 'shadow', vfxColor: '#4a1458', description: 'Projectile, stacking chilled (−5% spd each, max 5)' }),
      makeAbility({ id: 'eternal_night', name: 'Eternal Night', combo: 'down,up,down,up,attack', baseDamage: 25, scaleStat: 'INT', scaleAmount: 0.4, cooldownMs: 120000, cost: 90, isGroundTarget: true, aoeRadius: 240, effects: { silence: { magnitude: 1, durationMs: 6000 }, dot: { magnitude: 25, durationMs: 6000 } }, damageType: 'shadow', vfxColor: '#030712', description: '240u zone, silence + shadow DoT 6s' }),
    ],
    rmb: makeAbility({ id: 'shadow_cloak', name: 'Shadow Cloak', combo: 'block+attack', cooldownMs: 20000, cost: 0, effects: { stealth: { magnitude: 1, durationMs: 2000 }, speed_boost: { magnitude: -0.4, durationMs: 2000 } }, vfxColor: '#4a1458', description: '2s: 60% speed, untargetable by ranged' }),
  },
  {
    id: 'chef',
    name: 'Chef',
    color: '#f48fb1',
    initial: 'C',
    stats: { STR: 10, DEX: 10, CON: 12, INT: 14, WIS: 10, CHA: 16 },
    hpMax: 110,
    armor: 6,
    magicResist: 6,
    moveSpeed: 130,
    jumpPower: 550,
    damageType: 'physical',
    description: 'Utility support with dish buffs',
    strategy: {
      preferRange: 'mid',
      aggressionPct: 0.5,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.4,
      abilities: {
        1: { priority: 6, useAtCloseRange: true },
        2: { priority: 5, useAtCloseRange: true },
        3: { priority: 8, maxHpPct: 0.6, retreatToUse: true },
        4: { priority: 6, useAtLongRange: true },
        5: { priority: 7, minResourcePct: 0.6 },
        rmb: { priority: 4 },
      },
    },
    resource: {
      name: 'Stamina',
      max: 100,
      startValue: 100,
      regenIdle: 4,
      regenCombat: 2,
      decayRate: 0,
      color: '#f9a8d4',
    },
    abilities: [
      makeAbility({ id: 'feast', name: 'Feast', combo: 'down,down,attack', cooldownMs: 30000, cost: 40, aoeRadius: 180, vfxColor: '#f48fb1', description: 'Apply dish buff to all allies 180u' }),
      makeAbility({ id: 'ladle_bash', name: 'Ladle Bash', combo: 'right,right,attack', baseDamage: 25, scaleStat: 'STR', scaleAmount: 0.5, cooldownMs: 3000, cost: 10, range: 60, effects: { daze: { magnitude: 1, durationMs: 500 } }, damageType: 'physical', vfxColor: '#f48fb1', description: 'Melee, daze 0.5s' }),
      makeAbility({ id: 'hot_soup', name: 'Hot Soup', combo: 'down,up,attack', baseDamage: 40, scaleStat: 'INT', scaleAmount: 0.5, cooldownMs: 10000, cost: 20, range: 240, isHeal: true, effects: { hot: { magnitude: 20, durationMs: 4000 } }, vfxColor: '#fde68a', description: 'Heal + regen 20/s × 4s on ally 240u' }),
      makeAbility({ id: 'spice_toss', name: 'Spice Toss', combo: 'left,right,attack', baseDamage: 10, scaleStat: 'INT', scaleAmount: 0.2, cooldownMs: 8000, cost: 15, isProjectile: true, projectileSpeed: 350, range: 300, effects: { blind: { magnitude: 1, durationMs: 2000 }, dot: { magnitude: 10, durationMs: 3000 } }, damageType: 'physical', vfxColor: '#fbbf24', description: 'Projectile, blind 2s + DoT' }),
      makeAbility({ id: 'signature_dish', name: 'Signature Dish', combo: 'down,up,down,up,attack', cooldownMs: 180000, cost: 60, isChannel: true, channelDurationMs: 2000, aoeRadius: 300, vfxColor: '#f9a8d4', description: 'Channel 2s, combine dish effects all allies 300u 20s' }),
    ],
    rmb: makeAbility({ id: 'pocket_dish', name: 'Pocket Dish', combo: 'block+attack', cooldownMs: 3000, cost: 0, vfxColor: '#f48fb1', description: 'Consume a dish for its buff (self)' }),
  },
  {
    id: 'leper',
    name: 'Leper',
    color: '#738d3f',
    initial: 'L',
    stats: { STR: 14, DEX: 10, CON: 18, INT: 8, WIS: 8, CHA: 6 },
    hpMax: 160,
    armor: 12,
    magicResist: 10,
    moveSpeed: 120,
    jumpPower: 500,
    damageType: 'necrotic',
    description: 'Diseased bruiser spreading infection',
    strategy: {
      preferRange: 'close',
      aggressionPct: 0.7,
      blockOnReaction: false,
      resourceStrategy: 'spend',
      retreatBelowHpPct: 0.2,
      abilities: {
        1: { priority: 7, minResourcePct: 0.15, useAtCloseRange: true },
        2: { priority: 6, useAtCloseRange: true },
        3: { priority: 9, maxHpPct: 0.5, useAtCloseRange: true },
        4: { priority: 5, useAtLongRange: true },
        5: { priority: 8, minResourcePct: 0.5 },
        rmb: { priority: 7 },
      },
    },
    resource: {
      name: 'Rot',
      max: 100,
      startValue: 0,
      regenIdle: 3,
      regenCombat: 3,
      decayRate: 0,
      color: '#65a30d',
    },
    abilities: [
      makeAbility({ id: 'plague_vomit', name: 'Plague Vomit', combo: 'down,down,attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 0.6, cooldownMs: 8000, cost: 15, aoeRadius: 150, effects: { infected: { magnitude: 1, durationMs: 3000 }, slow: { magnitude: 0.3, durationMs: 3000 } }, damageType: 'necrotic', vfxColor: '#65a30d', description: 'Cone 150u, infected DoT + slow 30% 3s' }),
      makeAbility({ id: 'diseased_claw', name: 'Diseased Claw', combo: 'right,right,attack', baseDamage: 30, scaleStat: 'STR', scaleAmount: 0.7, cooldownMs: 2000, cost: 5, range: 60, effects: { infected: { magnitude: 1, durationMs: 5000 }, dot: { magnitude: 10, durationMs: 5000 } }, damageType: 'necrotic', vfxColor: '#738d3f', description: 'Melee + infected DoT 5s' }),
      makeAbility({ id: 'necrotic_embrace', name: 'Necrotic Embrace', combo: 'down,up,attack', baseDamage: 50, scaleStat: 'STR', scaleAmount: 0.8, cooldownMs: 14000, cost: 25, range: 60, isHeal: true, damageType: 'necrotic', effects: { lifesteal: { magnitude: 1.0, durationMs: 0 } }, vfxColor: '#3f6212', description: 'Grab + heal for damage dealt' }),
      makeAbility({ id: 'contagion', name: 'Contagion', combo: 'left,right,attack', cooldownMs: 12000, cost: 20, range: 300, effects: { infected: { magnitude: 1, durationMs: 8000 } }, vfxColor: '#4d7c0f', description: 'Infect target; jumps to nearby on death/spread' }),
      makeAbility({ id: 'rotting_tide', name: 'Rotting Tide', combo: 'down,up,down,up,attack', baseDamage: 30, scaleStat: 'CON', scaleAmount: 0.4, cooldownMs: 120000, cost: 50, isChannel: true, channelDurationMs: 3000, aoeRadius: 180, damageType: 'necrotic', isSummon: true, vfxColor: '#1a2e05', description: 'Channel 3s PB 180u; killed enemies revive as husks 5s' }),
    ],
    rmb: makeAbility({ id: 'miasma', name: 'Miasma', combo: 'block+attack', cooldownMs: 2000, cost: 0, aoeRadius: 90, effects: { dot: { magnitude: 5, durationMs: 100 } }, damageType: 'necrotic', vfxColor: '#4d7c0f', description: 'Toggle aura: 5+0.2×CON necrotic DPS 90u' }),
  },
  {
    id: 'master',
    name: 'Master',
    color: '#e0e0e0',
    initial: 'M',
    stats: { STR: 12, DEX: 12, CON: 14, INT: 14, WIS: 14, CHA: 12 },
    hpMax: 140,
    armor: 10,
    magicResist: 10,
    moveSpeed: 135,
    jumpPower: 570,
    damageType: 'physical',
    description: 'Prestige hybrid; adapts to one of 5 primed classes',
    strategy: {
      preferRange: 'mid',
      aggressionPct: 0.6,
      blockOnReaction: true,
      resourceStrategy: 'spend',
      abilities: {
        1: { priority: 7, useAtCloseRange: true },
        2: { priority: 5 },
        3: { priority: 8, minResourcePct: 0.2 },
        4: { priority: 4 },
        5: { priority: 9, minResourcePct: 0.5 },
        rmb: { priority: 3 },
      },
    },
    resource: {
      name: 'Mastery',
      max: 200,
      startValue: 200,
      regenIdle: 5,
      regenCombat: 3,
      decayRate: 0,
      color: '#e5e7eb',
    },
    abilities: [
      makeAbility({ id: 'chosen_strike', name: 'Chosen Strike', combo: 'down,down,attack', baseDamage: 40, scaleStat: 'STR', scaleAmount: 1.0, cooldownMs: 3000, cost: 15, range: 200, damageType: 'physical', vfxColor: '#e0e0e0', description: 'Ranged or melee by primed class' }),
      makeAbility({ id: 'chosen_utility', name: 'Chosen Utility', combo: 'right,right,attack', cooldownMs: 8000, cost: 25, isTeleport: true, teleportDist: 120, vfxColor: '#d1d5db', description: 'Utility from primed class' }),
      makeAbility({ id: 'chosen_nuke', name: 'Chosen Nuke', combo: 'down,up,attack', baseDamage: 90, scaleStat: 'INT', scaleAmount: 1.1, cooldownMs: 12000, cost: 40, aoeRadius: 100, damageType: 'magical', vfxColor: '#9ca3af', description: 'Burst from primed class +10%' }),
      makeAbility({ id: 'eclipse', name: 'Eclipse', combo: 'left,right,attack', cooldownMs: 20000, cost: 40, vfxColor: '#6b7280', description: '5s: slots cycle all primed-class versions' }),
      makeAbility({ id: 'apotheosis', name: 'Apotheosis', combo: 'down,up,down,up,attack', cooldownMs: 240000, cost: 100, effects: { damage_boost: { magnitude: 0.2, durationMs: 10000 }, hot: { magnitude: 20, durationMs: 10000 } }, vfxColor: '#f9fafb', description: '10s: all CDs halved, +20% dmg, 2% HP/s heal' }),
    ],
    rmb: makeAbility({ id: 'class_swap', name: 'Class Swap', combo: 'block+attack', cooldownMs: 1000, cost: 0, vfxColor: '#e0e0e0', description: 'Cycle primed class' }),
  },
];

export function getGuild(id: string): GuildDef {
  const g = GUILDS.find(g => g.id === id);
  if (!g) throw new Error(`Unknown guild: ${id}`);
  return g;
}

export const DRUID_WOLF_ABILITIES: AbilityDef[] = [
  makeAbility({
    id: 'wolf_maul', name: 'Maul', combo: 'down,down,attack',
    baseDamage: 55, scaleStat: 'STR', scaleAmount: 0.9,
    range: 70, knockdown: true, damageType: 'physical',
    vfxColor: '#8B4513', description: 'Heavy swipe, knocks down target',
  }),
  makeAbility({
    id: 'wolf_charge', name: 'Charge', combo: 'right,right,attack',
    baseDamage: 35, scaleStat: 'STR', scaleAmount: 0.6,
    range: 180, isTeleport: true, teleportDist: 180,
    knockbackForce: 200, damageType: 'physical',
    vfxColor: '#A0522D', description: 'Rush forward, knockup first enemy hit',
  }),
  makeAbility({
    id: 'wolf_roar', name: 'Roar', combo: 'down,up,attack',
    baseDamage: 0, aoeRadius: 150, cooldownMs: 8000, cost: 20,
    effects: {
      slow: { magnitude: 0.4, durationMs: 2000 },
      fear: { magnitude: 1, durationMs: 1000 },
    },
    damageType: 'physical', vfxColor: '#FFD700',
    description: '150u AoE slow + brief fear',
  }),
  makeAbility({
    id: 'wolf_rend', name: 'Rend', combo: 'left,right,attack',
    baseDamage: 20, scaleStat: 'STR', scaleAmount: 0.4,
    range: 75, damageType: 'physical',
    effects: { dot: { magnitude: 8, durationMs: 3000 } },
    vfxColor: '#DC143C', description: 'Melee + stacking bleed DoT',
  }),
  makeAbility({
    id: 'wolf_primal_fury', name: 'Primal Fury', combo: 'down,up,down,up,attack',
    baseDamage: 0, cooldownMs: 90000, cost: 60,
    effects: {
      damage_boost: { magnitude: 0.4, durationMs: 6000 },
      speed_boost: { magnitude: 0.2, durationMs: 6000 },
    },
    vfxColor: '#FF4500', description: '6s berserk: +40% dmg +20% speed',
  }),
];

export const DRUID_WOLF_RMB: AbilityDef = makeAbility({
  id: 'wolf_revert', name: 'Revert', combo: 'block+attack',
  cooldownMs: 0, cost: 0,
  vfxColor: '#228B22', description: 'Exit wolf form, restore stats',
});
